nodeLinker: node-modules

# Commented out to use Corepack instead of committed binary
# yarnPath: .yarn/releases/yarn-3.2.4.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
